### ISSUE TITLE
Using `graphql-request` to interact with local network

### ISSUE THREAD

**Issue by teddyjfpender** [o1-labs/wait-for-mina-network-action#83]
When using `wait-for-mina-network-action` in a Github workflow, I'm using `graphql-request` to abstract over querying the Mina node in a TypeScript provider class. Each time I query the node I get a `ClientError`. Unsure if this is a `graphql-request` specific error or if there are preferred ways of interacting with the local network in CI? 

Steps to reproduce:
```typescript
import { GraphQLClient } from 'graphql-request'

interface AccountData {
  account: {
      balance: { total: number }
      nonce: number
      inferredNonce: number
      delegate: string
      publicKey: string
    }
}

const client = new GraphQLClient('http://localhost:8080/graphql', {
  errorPolicy: 'all'
})
const data = await client.rawRequest<AccountData>(query, {
  publicKey: 'B62qrBNbJnwr7BR2vkdw43CjzctaLEvG66oNRH9zB72ABcQRFBzYKCT' // any public key with an account from the local-network
})
```

The error thrown by `graphql-request` looks like this:
```bash
Error in getAccountInfo: ClientError: GraphQL Error (Code: 200): 
...
response: {
    error: '{"data":{"account":{"balance":{"total":"1550000000000"},"nonce":"0","inferredNonce":"0","delegateAccount":{"publicKey":"B62qrBNbJnwr7BR2vkdw43CjzctaLEvG66oNRH9zB72ABcQRFBzYKCT"},"publicKey":"B62qrBNbJnwr7BR2vkdw43CjzctaLEvG66oNRH9zB72ABcQRFBzYKCT"}}}',
    status: 200,
    headers: Headers { [Symbol(map)]: [Object: null prototype] }
  },
  request: {
    query: '\n' +
      '      \n' +
      '  query accountBalance($publicKey: PublicKey!) {\n' +
      '    account(publicKey: $publicKey) {\n' +
      '      balance {\n' +
      '        total\n' +
      '      },\n' +
      '      nonce\n' +
      '      inferredNonce\n' +
      '      delegateAccount {\n' +
      '        publicKey\n' +
      '      }\n' +
      '      publicKey\n' +
      '    }\n' +
      '  }\n' +
      '\n' +
      '    ',
    variables: {
      publicKey: 'B62qrBNbJnwr7BR2vkdw[43](https://github.com/palladians/pallad/actions/runs/7338856887/job/19982045107#step:11:44)CjzctaLEvG66oNRH9zB72ABcQRFBzYKCT'
    }
  }
}
```

Notes:
- The query works fine when run from the command line!

**Comment by shimkiv** [comment]
Hey @teddyjfpender thanks for reporting this.

> When using wait-for-mina-network-action in a Github workflow, I'm using graphql-request to abstract over querying the Mina node in a TypeScript provider class.

I'm not sure this is the correct repository for the issue/discussion you're raising unless you're 100% sure that this CI step is causing the issues and works well without it.
This repository contains sources for GitHub Actions `step` that can be used in your CI workflow to wait for the blockchain network readiness, nothing else, it should not (and I'm pretty sure it doesn't) impact your other CI steps.

> The query works fine when run from the command line!

You mean same script, when is executed locally against same local blockchain, works without issues?

> The error thrown

I'll take a look but for some reason, as you can tell, your client interprets response as error even though response status code is HTTP 200 and it contains actual requested payload.

**Comment by shimkiv** [comment]
@teddyjfpender can you please also share your GitHub Actions CI workflow file?

**Comment by shimkiv** [comment]
@teddyjfpender BTW, all responses from Mina's GraphQL are wrapped into `data` property. Maybe you just need to configure client to deserialise it properly instead of trying to cast response to `interface AccountData`?

**Comment by teddyjfpender** [comment]
@shimkiv I managed to fix it with some fighting. Green CI run [here](https://github.com/palladians/pallad/actions/runs/7343933051/job/19995128392) if you're interested. Adding a custom [fetch function](https://github.com/palladians/pallad/blob/7c17fda79c1799efffe511df116bae60804e0127/packages/mina-graphql/src/Providers/AccountInfo/AccountInfoProvider.ts#L16-L31) seemed to do the trick.

Apologies again for bringing up the issue here, closing now 🙏
